### ISSUE TITLE
Refactor pipeline to enable build for macOS

### ISSUE THREAD

**Issue by Koufan-De-King** [stephane-segning/lynx-scanner-app#3]
Related to/Adds on to:
- #1

**Comment by stephane-segning** [comment]
I did an implementation in https://github.com/stephane-segning/lynx-scanner-app/actions/runs/9704988090/job/26786293193

The idea was to use a runtime machine. So problem half fixed, but now should be tested:
https://github.com/stephane-segning/lynx-scanner-app/releases/tag/v1.0.1

**Comment by Koufan-De-King** [comment]
Thank you sir @stephane-segning 

Tested and found it does not work on my mac.
<img width="675" alt="Screenshot 2024-06-28 at 08 44 02" src="https://github.com/stephane-segning/lynx-scanner-app/assets/148069250/42ae86b0-0b4e-4c8f-b8a8-9ec244aadd1a">

Specifications:
<img width="639" alt="Screenshot 2024-06-28 at 09 02 57" src="https://github.com/stephane-segning/lynx-scanner-app/assets/148069250/589807c1-04f6-44df-bda6-9d0784cf55ef">

I gathered that
<img width="710" alt="Screenshot 2024-06-28 at 09 06 53" src="https://github.com/stephane-segning/lynx-scanner-app/assets/148069250/49688125-f7dc-44d9-a361-8f5d43ec48d4">

So we need to make it work for the older architecture of mac, namely ```x64``` with the Apple silicon chip.

**Comment by Koufan-De-King** [comment]
Tested again. Done and dusted. Thank you @stephane-segning
